server:
  port: 8081
  servlet:
    path: /
logging:
  level:
    com.saber: debug
  #  org.springframework: debug
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/people
    username: root
    password: root
mybatis:
 # configuration:
  #  map-underscore-to-camel-case: true
  type-aliases-package: com.saber.pojo
  #mapper-locations: mapper/*.xml